apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cicd-app
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test-cicd-app
  template:
    metadata:
      labels:
        app: test-cicd-app
    spec:
      containers:
        - name: app
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
              name: web
